version: '3.9'

services:
  
  pg:
    image: postgres:16.2
    container_name: gerello_pg
    restart: always
    environment:
      - POSTGRES_DB=gerello-pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"